export const ACCOUNT_UPDATE = "ACCOUNT_UPDATE";

export const CONTRACT_LOADED = "CONTRACT_LOADED";

export const ON_PERSONAL_DATA_LOADED = "ON_PERSONAL_DATA_LOADED";

export const ON_CONTRACT_DATA_LOADED = "ON_CONTRACT_DATA_LOADED";
